name: Workflow Experiments

on: [push, pull_request]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }} >> output.txt

