name: Workflow Experiments

on: [push, pull_request]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Execute python script
      run: |
        python generateReadme.py

    - name: Commit list of files back into the repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add README_generated.md
        git diff-index --quiet HEAD || git commit -m "Updating generated README"
        git push

