name: Workflow Experiments

on: [push, pull_request]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }} >> output.txt

    - name: Commit list of files back into the repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add -A
        git commit -m "Updating file list"
        git push

